on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: curl -L -o /tmp/mars.jar http://courses.missouristate.edu/KenVollmar/MARS/MARS_4_5_Aug2014/Mars4_5.jar
      - run: cd co-tester && MARS_JAR=/tmp/mars.jar cargo build
