on: push
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-unknown-linux-gnu, x86_64-pc-windows-gnu]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - if: matrix.target == 'x86_64-pc-windows-gnu'
        run: sudo apt install mingw-w64
      - run: |
          rustup update
          rustup target add ${{ matrix.target }}
          curl -L -o /tmp/mars.jar http://courses.missouristate.edu/KenVollmar/MARS/MARS_4_5_Aug2014/Mars4_5.jar
          cd co-tester
          MARS_JAR=/tmp/mars.jar cargo build --target ${{ matrix.target }}
